version: 2.1

jobs:
  build:
    steps :
      - checkout
      - run: npm i
      - save_cache:
          keys : "npm dependencies"
          paths :
            - /src/node_modules
      - run: npm run lint
  test :
    steps :
      - checkout
      - restore_cache:
          keys: "npm dependencies"
      - run: npm i
      - run: npm run test
  analyze:
    steps :
      - checkout
      - restore_cache:
          keys: "npm dependencies"
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test  