version: 2.1

jobs:
  buil:
    docker :
      image: circleci/node:13.8.0
    steps :
      - checkout
      - run: npm i
      - save_cache:
          keys : "npm dependencies"
          paths :
            - /src/node_modules
      - run: npm run lint
  test :
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: "npm dependencies"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: "npm dependencies"
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - buil
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test  